//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<Post> Post { get; set; }
    
        public virtual ObjectResult<SP_Categorias_Result> SP_Categorias(Nullable<int> parametroNumerico, string parametroTexto)
        {
            var parametroNumericoParameter = parametroNumerico.HasValue ?
                new ObjectParameter("ParametroNumerico", parametroNumerico) :
                new ObjectParameter("ParametroNumerico", typeof(int));
    
            var parametroTextoParameter = parametroTexto != null ?
                new ObjectParameter("ParametroTexto", parametroTexto) :
                new ObjectParameter("ParametroTexto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Categorias_Result>("SP_Categorias", parametroNumericoParameter, parametroTextoParameter);
        }
    }
}
